on:
  push:
    branches:
      - main
jobs:
  sample-gradle:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run Build
        run: |
          cd sample-gradle
          ./gradlew jig
      - name: Prepare GitHub Pages
        run: |
          mkdir _site/
          mv sample-gradle/build/jig _site/sample-gradle
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
  sample-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('sample-maven/pom.xml', 'sample-maven/.mvn/wrapper/maven-wrapper.properties') }}
      - name: Run Build
        run: |
          cd sample-maven
          ./mvnw package
  sample-maven-multi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('sample-maven-multi/pom.xml', 'sample-maven-multi/.mvn/wrapper/maven-wrapper.properties') }}
      - name: Run Build
        run: |
          cd sample-maven-multi
          ./mvnw package
