on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy-github-pages:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    steps:
      - uses: actions/checkout@v3

      # 画像出力のためにGraphvizを入れます。
      # 自分で apt install してもいいです。DOT（テキスト）でいい場合は不要です。
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      # 何をするにしてもJDKが必要
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # GradleやMavenのキャッシュです。 actions/gradle-build-action などを使用する場合は自分でやらなくていいです。
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/.mvn/wrapper/maven-wrapper.properties') }}

      # ここからがJIGドキュメントの生成です。
      - name: sample-gradleのビルド
        run: |
          cd sample-gradle
          ./gradlew jig

      - name: sample-mavenのビルド
        run: |
          cd sample-maven
          ./mvnw package

      - name: sample-maven-multiのビルド
        run: |
          cd sample-maven-multi
          ./mvnw package

      # デプロイのために生成されたJIGドキュメントを _site/ に移動しています。
      - name: Prepare GitHub Pages
        run: |
          mv sample-gradle/build/jig _site/sample-gradle
          mv sample-maven/target/jig _site/sample-maven
          mv sample-maven-multi/target/jig _site/sample-maven-multi

      # JIGドキュメントをデプロイします。
      # ここではGitHub Pagesに置いています。
      # 実際のプロジェクトではGitHub ActionsのArtifact、S3、Slackなどが使われています。
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
